name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: guide/abcd
          stage: main
          yaml: >
            name: cloudtype-frontend-template

            app: web

            options:
              nodeversion: 14
              spa: true
              buildenv:
                - name: REACT_APP_WAITLIST_API_URL
                  value: https://port-0-cloudtype-backend-template-3ucske2clk6cotcb.exp0.cloudtype.app/api/guests
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: react
